title: Kevin Li
description: AI Security | Agentic AI Risk | Software Engineering
theme: minima

author: Kevin Li
email: kevin.li3@mail.mcgill.ca

header_pages:
  - research.md
  - publications.md
  - cv.md
  - contact.md
